{"id":"jgk0wgxhbjjsohuo1j4b1qy","title":"Exception Handling","desc":"","updated":1641422448644,"created":1641422448644,"custom":{},"fname":"s.l.python.flow.exception-handling","type":"note","vault":{"fsPath":"DevLog"},"contentHash":"ccf327bbb239d3dc067c10c5bc71235a","links":[],"anchors":{"exception-handling":{"type":"header","text":"Exception Handling","value":"exception-handling","line":9,"column":0,"depth":2}},"children":[],"parent":"z8urjeawplya8pgrucqyvzv","data":{}}
